language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

jobs:
  include:
    - stage: test
      script:
        - npm run lint:nofix
        - npm run test:unit

    - stage: build
      install:
        - npm install
        - npm run build

    - stage: deploy
      env:
        - VUE_APP_ALERTA_ENDPOINT="https://alerta-api.herokuapp.com"
      script: npm run build
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          target-branch: gh-pages
          local-dir: dist
          on:
            branch: master
