language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install
  - npm run build

script:
  - npm run lint:nofix
  - npm run test:unit

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    target-branch: gh-pages
    local-dir: dist
    on:
      branch: master
  - provider: releases
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    file_glob: true
    file: dist/**/*
    on:
      tags: true
